version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: python manage.py runserver_plus 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            -  "8000:8000"
        links:
            - db
            - redis
    redis:
        image: redis
    celery:
        build:
            context: .
            dockerfile: Dockerfile-celery
        links:
            - redis
