version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            -  "8000:8000"
        links:
            - db
            - celery
            - redis
    celery:
        build: .
        links:
            - redis
            - db
        depends_on:
            - redis
        volumes_from:
            - web
        command: su -m myuser -c "celery worker -A branches -l info"
    redis:
        image: redis:latest
