version: '2'
services:
    db:
        image: postgres
        volumes:
            - pgdata: /var/lib/postgresql/data/
    web:
        restart: always
        build: .
        command: ./docker/scripts/run_gunicorn.sh
        ports:
            -  "8000:8000"
        links:
            - db
            - redis
    celery:
        build: .
        links:
            - redis
            - db
            - web
        depends_on:
            - redis
            - web
        volumes_from:
            - web
        command: su -m myuser -c "celery worker -A branches -l info"
    redis:
        image: redis:latest
    stats:
        image: hopsoft/graphite-statsd
