# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digitalocean_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digitalocean_access_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digitalocean_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
