# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_auto_20160513_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gravatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
